apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rwsh5voqe-dotnet-basic 
  janus-idp.io/tekton: rwsh5voqe-dotnet-basic
  backstage.io/kubernetes-id: rwsh5voqe-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rwsh5voqe-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml